# Landing page details
title= "Tech blog of Mariachi in a jar 🍯"
description = "Notes on support engineering, Kubernetes, Rust, and systems."
default_language = "en"
theme = "tabi"

# The URL the site will be built for
base_url = "https://mariachiinajar.github.io"

compile_sass = true
build_search_index = false
generate_feeds = true
taxonomies = [{ name = "tags", feed = true }]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
